flaskdriver/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, DateField, SubmitField
from wtforms.validators import DataRequired

class SelectCategoriesForm(FlaskForm):
    select = SelectField("Choose a category", coerce=int, validators=[DataRequired()])
    submit = SubmitField("Submit")

class RefineForm(FlaskForm):
    min_date = DateField("Minimum Airdate (YYYY-MM-DD)", format='%Y-%m-%d')
    max_date = DateField("Maximum Airdate (YYYY-MM-DD)", format='%Y-%m-%d')
    value = SelectField("Value", coerce=int, choices=[(0, 'Select a value'),(200,"200"),(400, "400"),(600, "600"),(800, "800"),(1000, "1000")])
    submit = SubmitField("Refine")

flaskdriver/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flaskdriver.config import Config


app = Flask(__name__)
app.config.from_object(Config)

from flaskdriver.main.routes import main
app.register_blueprint(main)

flaskdriver/main/routes.py
from flask import Blueprint, render_template, url_for, redirect, request
from flaskdriver.forms import SelectCategoriesForm, RefineForm
from jService.api_handler import jService
from titlecase import titlecase

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
@main.route("/home", methods=["GET", "POST"])
def home():
    jservice = jService()
    jservice.build_search_url("categories", count=100)
    results = jservice.get_results()

    title = "Home"
    form = SelectCategoriesForm()
    form.select.choices = [(result['id'], titlecase(result['title'])) for result in results]
    form.select.choices = [(0, 'Select a category')] + form.select.choices

    if form.validate_on_submit():
        chosen_category = form.select.data
        return redirect(url_for("main.category", category_id=chosen_category))

    return render_template("home.html", title=title, form=form, results=results)


@main.route("/category/<category_id>", methods=["GET", "POST"])
def category(category_id):
    jservice = jService()
    jservice.build_search_url("clues", category=category_id)
    results = jservice.get_results()


    category = titlecase(results[0]['category']['title'])
    title = category
    form = RefineForm()

    if request.method == "POST":
        if form.min_date.data and form.max_date.data:
            if form.value.data:
                return redirect(url_for("main.category_by_value_and_date", category_name=category, category_id=category_id, value=form.value.data, min_date=form.min_date.data, max_date=form.max_date.data))
            else:
                return redirect(url_for("main.category_by_date", category_name=category, category_id=category_id, min_date=form.min_date.data, max_date=form.max_date.data))
        else:
            if form.value.data:
                return redirect(url_for("main.category_by_value", category_name=category, category_id=category_id, value=form.value.data))


    return render_template("category.html", title=title, form=form, results=results, category=category)


@main.route("/category/<category_name>/<category_id>/<value>")
def category_by_value(category_name, category_id, value):
    refine_id = 0
    jservice = jService()
    jservice.build_search_url("clues", category=category_id, value=value)
    results = jservice.get_results()
    return render_template("refined_category.html", title=category_name, results=results, category=category_name, category_id=category_id, value=value, refine_id=refine_id)


@main.route("/category/<category_name>/<category_id>/<min_date>/<max_date>")
def category_by_date(category_name, category_id, min_date, max_date):
    refine_id = 1
    jservice = jService()
    jservice.build_search_url("clues", category=category_id, min_date=min_date, max_date=max_date)
    results = jservice.get_results()
    return render_template("refined_category.html", title=category_name, results=results, category=category_name, category_id=category_id, refine_id=refine_id, min_date=min_date, max_date=max_date)


@main.route("/category/<category_name>/<category_id>/<value>/<min_date>/<max_date>")
def category_by_value_and_date(category_name, category_id, value, min_date, max_date):
    refine_id = 2
    jservice = jService()
    jservice.build_search_url("clues", category=category_id, value=value, min_date=min_date, max_date=max_date)
    results = jservice.get_results()
    return render_template("refined_category.html", title=category_name, results=results, category=category_name, category_id=category_id, refine_id=refine_id, value=value, min_date=min_date, max_date=max_date)

flaskdriver/templates/category.html
{% extends "layout.html" %}
{% block content %}

<div class="row">
    <a href="{{ url_for('main.home') }}"><button class="btn back-button"><- Back</button></a>
</div>

<div class="row">
    <div class="col-md-4 refine-section">
        <form method="POST">
            <div class="row refine-div">
                <h3>Refine your results</h3>
                {{ form.hidden_tag() }}

                {{ form.min_date.label(class="form-control-label my-2") }}
                {{ form.min_date(class="form-control form-control-sm my-2") }}

                {{ form.max_date.label(class="form-control-label my-2") }}
                {{ form.max_date(class="form-control form-control-sm my-2") }}

                {{ form.value.label( class="form-control-label my-2 mr-2") }}
                {{ form.value(id="value-select", class="form-select w-75 my-2") }}
                
                </br>

                {{ form.submit(class="btn my-2") }}
            </div>
        </form>
    </div>

    <script>
        document.getElementById("value-select").firstChild.setAttribute("disabled", "true");
        document.getElementById("value-select").firstChild.setAttribute("selected", "true");
    </script>

    <div class="col-md-7 results-div">
    
        <h3 id="results-title">{{ category }}</h3>

        {% for result in results %}

            <div class="card">
                <div class="card-body">
                    <div class="row justify-content-end">
                        <div class="clue-value">
                            <p>{{ result.value }}</p>
                        </div>
                        <div class="clue-airdate">
                            <p>{{ result.airdate[0:10] }}</p>
                        </div>
                    </div>
                    <h4 class="card-title">{{ result.question }}</h4>
                    <button type="button" class="btn" data-toggle="modal" data-target="#modal-{{ result.id }}">What is...</button>
                </div>
            </div>

            <div class="modal fade" id="modal-{{ result.id }}" tabindex="-1" role="dialog" aria-labelledby="clue-modal-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="clue-modal-label">{{ result.question }}</h5>
                        </div>
                        <div class="modal-body">
                            <p>What is... <strong>{{ result.answer }}</strong></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>
</div>


{% endblock content %}

flaskdriver/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="jumbotron">
    <h2 class="display-4">jTrivia: a trivia app that lets you explore Jeopardy trivia questions!</h2>
    <p class="lead">You can search for Jeopardy questions by category and further refine your results.</p>
    <hr class="my-4">

    <form method="POST">
        <div class="row my-3 justify-content-center">
        {{ form.hidden_tag() }}
        {{ form.select.label(class="form-control-label mr-3") }}
        {{ form.select(id="category-select", class="form-select") }}
        </div>
        <div class="row my-3 justify-content-center">
        {{ form.submit(class="btn") }}
        </div>
    </form>
        
</div>

<script>
    document.getElementById("category-select").firstChild.setAttribute("disabled", "true");
    document.getElementById("category-select").firstChild.setAttribute("selected", "true");
</script>


{% endblock content %}

flaskdriver/templates/layout.html
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    {% if title %}
        <title>jTrivia- {{ title }}</title>
    {% else %}
        <title>jTrivia</title>
    {% endif %}

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:500,700&display=swap" rel="stylesheet">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'main.css') }}">
    
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    
</head>
<body>
    
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">jTrivia</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.home') }}"><button class="btn">Home</button></a>
                    </li>
                </ul>
            </div>
        </nav>

    <div class="adjust-for-nav container-fluid">
        {% block content %}
        {% endblock content %}
    </div>


    <!-- Optional JavaScript -->
    <!-- Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

flaskdriver/templates/refined_category.html
{% extends "layout.html" %}
{% block content %}


<div class="row">
    <div class="col-md-4 back-div">
        <a href="{{ url_for('main.category', category_id=category_id) }}"><button class="btn back-button"><- Back</button></a>
    </div>

    {% if results %}
        <div class="col-md-7 results-div">
    
            <h3 id="results-title">{{ category }}</h3>
            {% if refine_id == 0 %}
                <h5 id="refine-title">Refined by Value({{ value }})</h5>
            {% elif refine_id == 1 %}
                <h5 id="refine-title">Refined by Date({{ min_date }} - {{ max_date }})</h5>
            {% else %}
                <h5 id="refine-title">Refined by Value({{ value }}) and Date({{ min_date }} - {{ max_date }})</h5>
            {% endif %}
    
            {% for result in results %}
    
                <div class="card">
                    <div class="card-body">
                        <div class="row justify-content-end">
                            <div class="clue-value">
                                <p>{{ result.value }}</p>
                            </div>
                            <div class="clue-airdate">
                                <p>{{ result.airdate[0:10] }}</p>
                            </div>
                        </div>
                        <h4 class="card-title">{{ result.question }}</h4>
                        <button type="button" class="btn" data-toggle="modal" data-target="#modal-{{ result.id }}">What is...</button>
                    </div>
                </div>
    
                <div class="modal fade" id="modal-{{ result.id }}" tabindex="-1" role="dialog" aria-labelledby="clue-modal-label" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="clue-modal-label">{{ result.question }}</h5>
                            </div>
                            <div class="modal-body">
                                <div>What is... <strong>{{ result.answer }}</strong></div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
    
            {% endfor %}
    
        </div>

    {% else %}

        <div class="col-md-7 results-div">
            <h3 id="results-title">{{ category }}</h3>
            <div class="card">
                <div class="card-body">
                    <h3>No results :(</h3>
                </div>
            </div>
            
        </div>

    {% endif %}
</div>


{% endblock content %}